### PR TITLE
Convert Fixnum to Integer in tests

### PR DESCRIPTION
**Pull request by pvalena**
to be compatible with Ruby 2.4.

### CODE REVIEW

**Comment by voxik** [comment]
Well, this might fix R2.4 compatibility but break older Rubies :/

**Comment by pvalena** [comment]
I know. It was ment just as FYI (affects only tests), because I'm not sure how to properly resolve it (use regexp or logic based on Ruby version?).

**Comment by JonRowe** [comment]
Thanks for attempting this, sorry its taken this long to get back to you, we have Ruby 2.4 compatibility in our specs so I'm closing this as stale.

**Comment by pvalena** [comment]
Looking forward to 2.6 chanes :)

**Pull request closed without merging**
